services:
- type: web
  name: rabbitmq
  env: docker
  port: 15672
  envVars:
  # - key: RABBITMQ_DEFAULT_USER
  #   value: admin
  # - key: RABBITMQ_DEFAULT_PASS
  #   generateValue: true
  # - key: RABBITMQ_ERLANG_COOKIE
  #   generateValue: true
  disk:
    name: rabbitmq
    mountPath: /var/lib/rabbitmq
    sizeGB: 10